import Foundation

// MARK: Points
struct RelativeLocation: Decodable {
    var city: String
    var state: String
}

struct LocationInfo: Decodable {
    var forecast: URL
    var relativeLocation: RelativeLocation
    var gridId: String
    var gridX: UInt
    var gridY: UInt
    var forecastZone: URL
}

// MARK: Forecast
struct ValueWithUnit: Decodable {
    var unitCode: String
    var value: Float
}

struct ForecastPeriod: Decodable {
    var name: String
    var startTime: Date
    var isDaytime: Bool
    var temperature: ValueWithUnit
    var probabilityOfPrecipitation: ValueWithUnit
    var windSpeed: String
    var windDirection: String
    var shortForecast: String
    var dewPoint: ValueWithUnit?
    var relativeHumidity: ValueWithUnit?
}

struct Forecast: Decodable {
    var periods: [ForecastPeriod]
}

// MARK: Alerts
struct Feature<Properties: Decodable>: Decodable {
    var properties: Properties
}

struct GeoJson<Properties: Decodable>: Decodable {
    var features: [Feature<Properties>]
}

struct AlertProperties: Decodable, Identifiable {
    var id: String
    var onset: Date?
    var ends: Date?
    var severity: String
    var certainty: String
    var urgency: String
    var event: String
    var description: String
    var instruction: String?
}

// MARK: Stations
struct StationProperties: Decodable {
    var stationIdentifier: String
}

// MARK: Observations
enum QualityControl: String, Decodable {
    case unverified = "Z"
    case coarse = "C"
    case screened = "S"
    case verified = "V"
    case rejected = "X"
    case questioned = "Q"
    case good = "G"
    case bad = "B"
    case interpolated = "T"
}

struct ValueWithQC: Decodable {
    var unitCode: String
    var value: Float?
    var qualityControl: QualityControl
}

enum Weather: String, Decodable, Hashable {
    case fogMist = "fog_mist"
    case dustStorm = "dust_storm"
    case funnelCloud = "funnel_cloud"
    case snowPellets = "snow_pellets"
    case iceCrystals = "ice_crystals"
    case icePellets = "ice_pellets"
    case dustWhirls = "dust_whirls"
    case snowGrains = "snow_grains"
    case sandStorm = "sand_storm"
    case volcanicAsh = "volcanic_ash"
    case dust, drizzle, fog, smoke, hail, haze, spray, rain, sand, snow, squalls, thunderstorms
    case unknown
}

struct MetarPhenomenon: Decodable, Hashable {
    var weather: Weather
}

enum CloudCover: String, Decodable {
    /// It's too foggy for cloud cover to be meaningful.
    case foggy = "VV"
    /// The sky is completely overcast.
    case overcast = "OVC"
    /// The sky is mostly covered with clouds.
    case broken = "BKN"
    /// The sky is partly covered with clouds.
    case scattered = "SCT"
    /// There are some clouds covering less than a quarter of the sky.
    case few = "FEW"
    /// There are no clouds detected below 12000 ft. Generated by automated stations.
    case clear = "CLR"
    /// There are no clouds visible to the naked eye. Included in man-made reports.
    case skyClear = "SKC"
}

struct MetarSkyCoverage: Decodable {
    var base: ValueWithUnit
    var amount: CloudCover
}

struct Observation: Decodable {
    var stationName: String
    var timestamp: Date
    var temperature: ValueWithQC
    var relativeHumidity: ValueWithQC
    var windChill: ValueWithQC
    var heatIndex: ValueWithQC
    var windSpeed: ValueWithQC
    var barometricPressure: ValueWithQC
    var presentWeather: Set<MetarPhenomenon>
    var cloudLayers: [MetarSkyCoverage?]
}
